


console.log("ahsan is here")

// VARIABLES ARE DECLARED BY THREE VAR,LET AND CONST 
// CONST IS WIDELY USED BECAUSE OF ITS LATEST FEATURES AND SCOPES
// VAR IS GLOBALLY SCOPED AND FUNCTION SCOPED AND CAN BE REASSIGNED AND REDECLARED and CREATE PROBLEM IN DEBUGGING
// LET ALSO IS BLOCK SCOPED AND CAN BE REASSIGNED BUT NOT DECLARED

var y=2
{
    let x=10
    console.log(x);
    console.log(y)
}

console.log(typeof(y))